apiVersion: v1
kind: Namespace
metadata:
  name: notes-app
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  namespace: notes-app
  labels:
    app: notes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes-app-container
        image: pranay801/notes-app:7
        ports:
          - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  selector:
    app: notes
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: notes-app-ing
  namespace: notes-app
spec:
  ingressClassName: nginx
  rules:
  - host: notes.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: notes-app-service
              port:
                number: 8000
